// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIw4nuKOZGb40hN1S3fXBoxI0PfZzbgwo',
    appId: '1:617821618725:web:e9056c58f28e8a8d9cf5cc',
    messagingSenderId: '617821618725',
    projectId: 'hr360-91796',
    authDomain: 'hr360-91796.firebaseapp.com',
    storageBucket: 'hr360-91796.firebasestorage.app',
    measurementId: 'G-M81PV3C93W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiRHL2UYdJfhxLVRPMQz7BYuU6fQ6osyE',
    appId: '1:617821618725:android:65c8196f4244ea139cf5cc',
    messagingSenderId: '617821618725',
    projectId: 'hr360-91796',
    storageBucket: 'hr360-91796.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3HbPyVv-z_c_S5aYKE9jaHFasTo84wGI',
    appId: '1:617821618725:ios:d5b5179d1bf19e9a9cf5cc',
    messagingSenderId: '617821618725',
    projectId: 'hr360-91796',
    storageBucket: 'hr360-91796.firebasestorage.app',
    iosBundleId: 'com.example.hr360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3HbPyVv-z_c_S5aYKE9jaHFasTo84wGI',
    appId: '1:617821618725:ios:d5b5179d1bf19e9a9cf5cc',
    messagingSenderId: '617821618725',
    projectId: 'hr360-91796',
    storageBucket: 'hr360-91796.firebasestorage.app',
    iosBundleId: 'com.example.hr360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIw4nuKOZGb40hN1S3fXBoxI0PfZzbgwo',
    appId: '1:617821618725:web:c84138368b379ad19cf5cc',
    messagingSenderId: '617821618725',
    projectId: 'hr360-91796',
    authDomain: 'hr360-91796.firebaseapp.com',
    storageBucket: 'hr360-91796.firebasestorage.app',
    measurementId: 'G-0K8LBQ3F0X',
  );
}
